{
 "title": "MLE-Project",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Время выполнения процесса",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Резидентный набор памяти",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AVG predictions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "main_app_predictions_sum{instance=\"fastapi_app:1702\", job=\"scrapping-main-app\"}/main_app_predictions_count{instance=\"fastapi_app:1702\", job=\"scrapping-main-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во запросов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "main_app_predictions_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Длительность запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантили ответов модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов на предсказание в мин.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов к сервису",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{instance=\"fastapi_app:1702\", job=\"scrapping-main-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}