services:
  main-app:  
    #используем файл с переменными среды
    env_file:
      - ./.env
    # собираем образ с помощью Dockerfile
    build:
      dockerfile: Dockerfile_ml_service
    # перенаправялем порты
    ports:
      - "${MAIN_APP_DOCKER_PORT}:${MAIN_APP_DOCKER_PORT}"
    ### добавьте:
    hostname: fastapi_app
  
  # добавьте описание сервиса Prometheus:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    hostname: prometheus 
  
  grafana:
    image: grafana/grafana
    env_file:
    - ./.env
    ports:
    - 3000:3000
    environment:
    - ADMIN_USER=${GRAFANA_USER}
    - ADMIN_PASSWORD=${GRAFANA_PASS}